### ISSUE TITLE
duplicate Standard tariffs

### ISSUE THREAD

**Issue by iddmaxwell** [jamiemax/optimisebills#28]
can we have just one Standard tariff per area/fuel type per supplier? 
as discussed, you are going to amend the script to load new tariffs along the following lines: 

read new tariff from API
IF there is a match on tariff name, area, fuel type in the new tariff table 
  THEN IF the tariff is not fixed
    THEN IF the rates have changed (std chg gas + std chg elec + rate gas + rate elec + rate elec night) is more than 0.05p different from before - NB might need to experiment to get the right tolerance - this might be too wide or narrow, I'm not sure. 
    THEN change the existing tariff in the new tariff table to 'replaced' and add the new variable rate tariff to the new tariff table
    ELSE (rates unchanged) leave existing tariff as is but set to 'Active'
  ELSE (tariff fixed) reset the existing fixed tariff to 'Active'
ELSE (no match) insert tariff into new tariff table

Separate script to copy to the old tariff table that i'm still currently using.

**Comment by Will-Newton** [comment]
Do we need to keep old tariff rates as tariff records if they're duplicated on the clients historical energy records?

**Comment by iddmaxwell** [comment]
read new tariff from new db
IF there is a match in old db on tariff name, area, fuel type, status (ACTIVE) 
THEN IF the tariff is not fixed (i.e. variable) 
If the tariff is ACTIVE 
THEN IF the rates have changed (std chg gas + std chg elec + rate gas + rate elec + rate elec night) is more than 0.05p different from before - NB might need to experiment to get the right tolerance - this might be too wide or narrow, I'm not sure. 
THEN change the existing tariff in the old db tariff table to 'replaced' and add the new variable rate tariff to the new tariff table as ACTIVE
ELSE if the tariff not ACTIVE (i.e. in use)
THEN set tariff to IN USE in the old db 
ELSE (rates unchanged) leave existing tariff as is (i.e. already ACTIVE)
ELSE (tariff fixed) reset the existing fixed tariff to 'Active'
ELSE (no match) insert tariff into old db tariff table

**Comment by Will-Newton** [comment]
Done

**Comment by iddmaxwell** [comment]
I think this is still an issue.  There are still duplicate Standard tariffs, e.g. for SSE, Dual Fuel, Manweb.

**Comment by iddmaxwell** [comment]
I can see that one of the duplicate Standard tariffs has been relabelled 'replaced' as I would expect the above logic to do.   However when we discussed you said that all the Standard tariff records would be updated at the same time by the same logic. 
This tariff appears on UK Power so must appear on the API too, but does not appear in our tariff table: 
**gas** 
Standing charge  15.660p  a day   (16.443p a day inc. VAT) 
Unit rate  3.830p  per kWh   (4.022p inc. VAT)  
**Electricity**
Standing charge  15.660p  a day  (16.443p a day inc. VAT)  
Day rate  14.860p  per kWh  (15.603p inc. VAT) 

The above logic should insert this current rate tariff and then change the status of all the existing ones to 'replaced'

**Comment by Will-Newton** [comment]
Which tariff are those rates for?

**Comment by Will-Newton** [comment]
The rates look the same in the tariff table. I've updated the duplicates to 'replaced'.

**Comment by iddmaxwell** [comment]
Corrected text from my email: 
SSE Standard, Manweb.  This might be just one example of others with the same issue. 
The current rates in the tariff table look the same but there is one on the API that has different rates to the latest ones in the tariff table.  The API latest current rate for the Standard tariff should be loaded and marked as 'active'

**Comment by Will-Newton** [comment]
SSE Standard on here is the same as on the tariff table:
http://services.ukpower.co.uk/home_energy/api/quotes.xml?api_key=8B34-7EDA-E529-B25D-8755&limit=0&postcode=l4%202rb&compare_type=all_switchable&region=10&electricity_usage_kwh=2780&electricity_usage_method=kwh

**Comment by iddmaxwell** [comment]
OK thanks it looks like it's now fixed - most of the duplicates have gone.  Although I found  SSE Swalec Standard has two tariffs for Manweb Dual Fuel.  Should one of these be getting automatically reset to Replaced?
Also I think the rates are still being rounded to 2dp.   
I don't have time to check more now, but can you look at these issues?

**Comment by iddmaxwell** [comment]
OK thanks it looks like it's now fixed - most of the duplicates have gone.  Although I found  SSE Swalec Standard has two tariffs for Manweb Dual Fuel.  Should one of these be getting automatically reset to Replaced?
Also I think the rates are still being rounded to 2dp.   
I don't have time to check more now, but can you look at these issues?

**Comment by iddmaxwell** [comment]
OK thanks it looks like it's now fixed - most of the duplicates have gone.  Although I found  SSE Swalec Standard has two tariffs for Manweb Dual Fuel.  Should one of these be getting automatically reset to Replaced?
Also I think the rates are still being rounded to 2dp.   
I don't have time to check more now, but can you look at these issues?

**Comment by iddmaxwell** [comment]
OK thanks it looks like it's now fixed - most of the duplicates have gone.  Although I found  SSE Swalec Standard has two tariffs for Manweb Dual Fuel.  Should one of these be getting automatically reset to Replaced?
Also I think the rates are still being rounded to 2dp.   
I don't have time to check more now, but can you look at these issues?

**Comment by iddmaxwell** [comment]
OK thanks it looks like it's now fixed - most of the duplicates have gone.  Although I found  SSE Swalec Standard has two tariffs for Manweb Dual Fuel.  Should one of these be getting automatically reset to Replaced?
Also I think the rates are still being rounded to 2dp.   
I don't have time to check more now, but can you look at these issues?

**Comment by Will-Newton** [comment]
3dp issue is resolved now. Will see the change after the next tariff load.

**Comment by Will-Newton** [comment]
THe duplicates should all have gone. I thought they'd come back, but they haven't. They were cleared a couple of weeks ago.
